---
application:
  name: "eventually-podcast"
  project: "eventually-podcast"
  organization: "QoveryCommunity"
routers:
- name: "main-eventually-podcast"
  routes:
  - application_name: "eventually-podcast"
    paths:
    - "/*"
