name: sample-monorepo

static_sites:
- name: frontend
  environment_slug: html
  github:
    repo: modernmediagrp/sample-monorepo
    branch: main
    deploy_on_push: true
  source_dir: frontend
  index_document: hello.html
  error_document: error.html
  routes:
  - path: /

- name: landing
  github:
    repo: modernmediagrp/sample-monorepo
    branch: main
    deploy_on_push: true
  source_dir: landing
  dockerfile_path: landing/Dockerfile
  output_dir: /app
  error_document: error.html
  routes:
  - path: /landing

- name: frontend-pp
  github:
    repo: modernmediagrp/sample-monorepo
    branch: main
    deploy_on_push: true
  source_dir: frontend-pp
  dockerfile_path: frontend-pp/Dockerfile
  output_dir: /app
  error_document: error.html
  routes:
  - path: /frontend-pp

services:
- name: frontend-rr
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: modernmediagrp/sample-monorepo
  source_dir: frontend-rr
